### PR TITLE
Fix panic catching in launcher and AKCert

### LINKED ISSUE #264: launcher: Don't defer os.Exit
https://github.com/google/go-tpm-tools/blob/master/launcher/launcher/main.go#L38-L40
when we defer `os.Exit()`, we swallow all panics because golang will process `defer`s before terminating.

See https://stackoverflow.com/questions/18963984/exit-with-error-code-in-go.

### PR DESCRIPTION
**Pull request by jkl73**
Fix #264 and #263 

Catch panic using defer recovery in launcher.
Return an empty MachineState pointer instead of nil in validateAKCert.

Signed-off-by: Jiankun Lu <jiankun@google.com>

### CODE REVIEW

File: launcher/launcher/main.go [hunk 1]
```diff
@@ -35,13 +35,22 @@ var launchSpec spec.LaunchSpec
 
 func main() {
 	var exitCode int
-	defer func() {
-		os.Exit(exitCode)
-	}()
 
 	logger = log.Default()
+	// default logger output to stderr
```
Comment (alexmwu) [inline launcher/launcher/main.go:40]: stdout or stderr?

File: server/verify.go [hunk 2]
```diff
@@ -245,7 +245,7 @@ func validateAKPub(ak crypto.PublicKey, opts VerifyOpts) error {
 
 func validateAKCert(akCert *x509.Certificate, opts VerifyOpts) (*pb.MachineState, error) {
 	if len(opts.TrustedRootCerts) == 0 {
-		return nil, validateAKPub(akCert.PublicKey.(crypto.PublicKey), opts)
+		return &pb.MachineState{}, validateAKPub(akCert.PublicKey.(crypto.PublicKey), opts)
```
Comment (alexmwu) [inline server/verify.go:248]: I think `validateAKPub` should return `(*pb.MachineState, error)` instead of just `error`. That way we always get a non-nil MachineState xor a non-nil error. 

If for some reason we don't do this, we should explain why this is needed, since someone might try to "simplify" this.

Comment (alexmwu) [inline server/verify.go:248]: Please add a test case for this and ideally check that it fails and then passes after changing the code.

File: launcher/launcher/main.go [hunk 3]
```diff
@@ -35,13 +35,22 @@ var launchSpec spec.LaunchSpec
...
+	log.SetOutput(os.Stdout)
 	logger.Println("TEE container launcher initiating")
 
+	defer func() {
```
Comment (alexmwu) [inline launcher/launcher/main.go:44]: These defers seem convoluted. Why not just put the os.Exit at the bottom of the code? We don't need the `recover` if we do that.

File: launcher/launcher/main.go (hunk 1 above)
Comment (jkl73) [reply launcher/launcher/main.go:40]: log.Default() will print to stderr, I want it to output to stdout. I will make the comment more clear.

File: server/verify.go (hunk 2 above)
Comment (jkl73) [reply server/verify.go:248]: added

Comment (jkl73) [reply server/verify.go:248]: added

File: launcher/launcher/main.go (hunk 3 above)
Comment (jkl73) [reply launcher/launcher/main.go:44]: This way we can output panic to cloud logging for better debug.

File: launcher/launcher/main.go [hunk 4]
```diff
@@ -35,13 +35,22 @@ var launchSpec spec.LaunchSpec
 
 func main() {
 	var exitCode int
-	defer func() {
-		os.Exit(exitCode)
-	}()
 
 	logger = log.Default()
+	// default logger output to stderr, change it to stdout
```
Comment (alexmwu) [inline launcher/launcher/main.go:40]: nit: log.Default() outputs to stderr; change to stdout.

File: launcher/launcher/main.go (hunk 1 above)
Comment (alexmwu) [reply launcher/launcher/main.go]: any reason we want stdout instead

**Review by alexmwu — APPROVED** [review]

File: launcher/launcher/main.go (hunk 1 above)
Comment (jkl73) [reply launcher/launcher/main.go]: no particular, most of the log we output info, so stdout seems like a better fit.
